[build]
  base = "/opt/build/repo/code-pulse/client"
  publish = "dist"
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "18.0.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200